name: build-mcmc
on:
  push:
    tags:
      - "v*"          
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake ninja-build
      - name: Configure
        run: |
          mkdir -p build
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build -j4
      - name: Package
        run: |
          mkdir -p dist
          cp build/mcmc dist/mcmc
          chmod +x dist/mcmc
          tar -C dist -czf mcmc-linux-x86_64.tar.gz mcmc
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: mcmc-linux-x86_64.tar.gz
